# Generated by Django 6.0.5 on 2026-05-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "health_application",
            "0002_remove_patient_condition_healthrecord_doctor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaladvice",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("VOICE", "Voice"),
                    ("BOTH", "Text and Voice"),
                ],
                default="TEXT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="medicaladvice",
            name="source_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_advice",
                to="health_application.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="appointment_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
