# Generated by Django 6.0.5 on 2026-06-05 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_language_preferences(apps, schema_editor):
    Profile = apps.get_model("health_application", "Profile")
    Profile.objects.filter(language_preference="English").update(language_preference="en")
    Profile.objects.filter(language_preference="Kiswahili").update(language_preference="sw")


class Migration(migrations.Migration):

    dependencies = [
        ("health_application", "0003_medicaladvice_message_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicationreminder",
            options={"ordering": ["next_trigger_at", "reminder_time", "medicine_name"]},
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medication_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="last_triggered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="next_trigger_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="number_of_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("once", "Once"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("custom", "Custom days"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="medicationreminder",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(normalize_language_preferences, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("sw", "Kiswahili")],
                default="en",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MedicationIntakeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_intake_logs",
                        to="health_application.patient",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_logs",
                        to="health_application.medicationreminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reminder", "scheduled_for"),
                        name="unique_reminder_scheduled_intake",
                    )
                ],
            },
        ),
    ]
